# Generated by Django 4.2.6 on 2023-10-31 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(default=None, max_length=30)),
                ('birthday', models.DateField(default=None)),
                ('comment', models.CharField(default=None, max_length=150)),
            ],
        ),
    ]
