# Generated by Django 4.2.6 on 2023-10-31 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='birthday',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='comment',
            field=models.CharField(default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
