# Generated by Django 4.2.6 on 2023-11-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0006_alter_client_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='birthday',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='client',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
