# Generated by Django 4.2.6 on 2023-11-05 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0007_alter_client_birthday_alter_client_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='birthday',
            field=models.DateField(blank=True, default=''),
        ),
    ]
