# Generated by Django 4.2.7 on 2023-11-10 21:37

import clientapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0010_alter_client_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to=clientapp.models.user_directory_path),
        ),
    ]
