# Generated by Django 4.2.6 on 2023-11-12 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0011_client_image'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='client',
            table='Client',
        ),
    ]
