# Generated by Django 4.2.6 on 2023-11-25 07:19

import clientapp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0014_alter_client_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='', upload_to=clientapp.models.user_directory_path)),
            ],
            options={
                'db_table': 'ClientImage',
            },
        ),
        migrations.RemoveField(
            model_name='client',
            name='image',
        ),
        migrations.AddField(
            model_name='client',
            name='clientphoto_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='photo', to='clientapp.clientphoto'),
        ),
    ]
