# Generated by Django 4.2.6 on 2023-11-25 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0015_clientphoto_remove_client_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='clientphoto_id',
        ),
        migrations.AddField(
            model_name='clientphoto',
            name='client_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='photo', to='clientapp.client'),
        ),
    ]
