# Generated by Django 4.2.6 on 2023-11-28 15:49

import clientapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0016_remove_client_clientphoto_id_clientphoto_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientphoto',
            name='image',
            field=models.ImageField(null=True, upload_to=clientapp.models.user_directory_path),
        ),
    ]
