# Generated by Django 4.2.6 on 2023-11-28 16:03

import clientapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0017_alter_clientphoto_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientphoto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=clientapp.models.user_directory_path),
        ),
    ]
