# Generated by Django 4.2.6 on 2023-11-01 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staffapp', '0003_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('amount', models.IntegerField()),
                ('discount', models.FloatField()),
                ('id_commodity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventoryapp.commodity')),
                ('id_employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='staffapp.staff')),
            ],
        ),
    ]
