# Generated by Django 4.2.7 on 2023-11-07 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffapp', '0003_schedule'),
        ('inventoryapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id_commodity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commodity', to='inventoryapp.commodity'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff', to='staffapp.staff'),
        ),
    ]
