# Generated by Django 4.2.7 on 2023-11-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0003_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.FloatField(default=None, null=True),
        ),
    ]
