# Generated by Django 4.2.6 on 2023-11-12 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0004_alter_order_discount'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='commodity',
            table='Commodity',
        ),
        migrations.AlterModelTable(
            name='order',
            table='Order',
        ),
    ]
