# Generated by Django 4.2.6 on 2023-11-26 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventoryapp', '0005_alter_commodity_table_alter_order_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff', to=settings.AUTH_USER_MODEL),
        ),
    ]
