# Generated by Django 4.2.6 on 2023-11-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0007_alter_commodity_price_alter_order_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddConstraint(
            model_name='commodity',
            constraint=models.CheckConstraint(check=models.Q(('amount__gte', 0)), name='amount_commodity_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='commodity',
            constraint=models.CheckConstraint(check=models.Q(('price__gt', 0)), name='price_commodity_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('amount__gte', 0)), name='amount_order_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('discount__range', [0, 99])), name='discount_order_range'),
        ),
    ]
