# Generated by Django 4.2.6 on 2023-11-01 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='access_level',
            field=models.IntegerField(),
        ),
    ]
