# Generated by Django 4.2.6 on 2023-11-01 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffapp', '0002_alter_staff_access_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('id_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffapp.staff')),
            ],
        ),
    ]
