# Generated by Django 4.2.6 on 2023-11-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffapp', '0003_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
