# Generated by Django 4.2.6 on 2023-11-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffapp', '0005_alter_staff_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='sex',
            field=models.CharField(choices=[('man', 'man'), ('woman', 'woman')], max_length=15),
        ),
    ]
