# Generated by Django 4.2.6 on 2023-11-26 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventoryapp', '0006_alter_order_id_employee'),
        ('recordapp', '0004_alter_record_id_staff'),
        ('staffapp', '0006_alter_staff_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='id_staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
