# Generated by Django 4.2.6 on 2023-11-01 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientapp', '0003_client_sex'),
        ('staffapp', '0003_schedule'),
        ('serviceapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('price', models.FloatField()),
                ('duration', models.IntegerField()),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientapp.client')),
                ('id_service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='serviceapp.service')),
                ('id_staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='staffapp.staff')),
            ],
        ),
    ]
