# Generated by Django 4.2.6 on 2023-11-30 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordapp', '0005_alter_record_options_record_time_slot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='time_slot',
            field=models.SmallIntegerField(),
        ),
    ]
