# Generated by Django 4.2.6 on 2023-12-01 09:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordapp', '0006_alter_record_time_slot'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='record',
            name='date__gte_today',
        ),
        migrations.AddConstraint(
            model_name='record',
            constraint=models.CheckConstraint(check=models.Q(('date__gte', datetime.date(2023, 12, 1))), name='date__gte_today'),
        ),
    ]
