# Generated by Django 4.2.6 on 2023-12-01 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0018_alter_clientphoto_image'),
        ('recordapp', '0007_remove_record_date__gte_today_record_date__gte_today'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='id_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='clientapp.client'),
        ),
    ]
