# Generated by Django 5.0.2 on 2024-02-29 07:22

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0018_alter_clientphoto_image'),
        ('recordapp', '0008_alter_record_id_client'),
        ('serviceapp', '0003_remove_service_id_resource_service_resources'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='record',
            name='date__gte_today',
        ),
        migrations.AddConstraint(
            model_name='record',
            constraint=models.CheckConstraint(check=models.Q(('date__gte', datetime.date(2024, 2, 29))), name='date__gte_today'),
        ),
    ]
